# Site wide configuration

title: Ram Laxman Yadav
locale: en_US
description: Ruby on Rails developer
logo: ram.jpeg
search: true
url: http://ramlaxmanyadav.github.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Ram Laxman Yadav
  avatar: bio-photo.jpg
  email: yadavramlaxman@gmail.com
  disqus-shortname:
  twitter: yadavramlaxman
  facebook: #username
  github: ramlaxmanyadav
  stackexchange: http://stackoverflow.com/users/3136258/ram
  linkedin: https://in.linkedin.com/pub/ram-laxman/76/531/717
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
